# Use official Python image
FROM python:3.9

# Set working directory inside the container
WORKDIR /app

# Copy application source code
COPY app/ /app

# Copy CSV files into the container
COPY data/ /data

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Set environment variables for data paths
ENV DATA_PATH="/data"
ENV OUTPUT_PATH="/output"

# Create an output directory
RUN mkdir -p $OUTPUT_PATH

# Run the application
CMD ["python", "main.py"]
